apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
  - type: Container
    default:
      cpu: "600m"
      memory: "512Mi"
    defaultRequest:
      cpu: "400m"
      memory: "350Mi"
