
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: crash
requireApproval: true
executionConfigs:
- usages:
  - PREDEPLOY
  - RENDER
  - ANALYSIS
  - POSTDEPLOY
  executionTimeout: 3600s
  defaultPool:
    # Placeholder: Replace with artifact bucket name.
    artifactStorage: artifactStorage
    # Placeholder: Replace with project number.
    serviceAccount: serviceAccount
- usages:
  - DEPLOY
  executionTimeout: 3600s
  privatePool:
    # Placeholder: Replace with worker pool name.
    workerPool: workerPool
    # Placeholder: Replace with artifact bucket name.
    artifactStorage: artifactStorage
    # Placeholder: Replace with project number.
    serviceAccount: serviceAccount
gke:
  # Placeholder: Replace with project ID, location, and cluster name.
  cluster: cluster
