// Copyright 2017 The Nomulus Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package google.registry.model.reporting;

import static com.google.common.base.Preconditions.checkArgument;
import static google.registry.util.CollectionUtils.nullToEmpty;
import static google.registry.util.CollectionUtils.nullToEmptyImmutableCopy;
import static google.registry.util.PreconditionsUtils.checkArgumentNotNull;

import com.google.common.annotations.VisibleForTesting;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;
import google.registry.model.Buildable;
import google.registry.model.EppResource;
import google.registry.model.ImmutableObject;
import google.registry.model.UnsafeSerializable;
import google.registry.model.annotations.OfyIdAllocation;
import google.registry.model.contact.ContactBase;
import google.registry.model.contact.ContactHistory;
import google.registry.model.domain.DomainBase;
import google.registry.model.domain.DomainHistory;
import google.registry.model.domain.Period;
import google.registry.model.eppcommon.Trid;
import google.registry.model.host.HostBase;
import google.registry.model.host.HostHistory;
import java.util.Optional;
import java.util.Set;
import javax.annotation.Nullable;
import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;
import org.apache.commons.lang3.BooleanUtils;
import org.hibernate.collection.internal.PersistentSet;
import org.joda.time.DateTime;

/**
 * A record of an EPP command that mutated a resource.
 *
 * <p>This abstract class has three subclasses that include the parent resource itself and are
 * persisted to Cloud SQL.
 */
@MappedSuperclass
@Access(AccessType.FIELD)
public abstract class HistoryEntry extends ImmutableObject
    implements Buildable, UnsafeSerializable {

  /** Represents the type of history entry. */
  public enum Type {
    CONTACT_CREATE,
    CONTACT_DELETE,
    CONTACT_DELETE_FAILURE,
    CONTACT_PENDING_DELETE,
    CONTACT_TRANSFER_APPROVE,
    CONTACT_TRANSFER_CANCEL,
    CONTACT_TRANSFER_REJECT,
    CONTACT_TRANSFER_REQUEST,
    CONTACT_UPDATE,
    /**
     * Used for history entries that were allocated as a result of a domain application.
     *
     * <p>Domain applications (and thus allocating from an application) no longer exist, but we have
     * existing domains in the system that were created via allocation and thus have history entries
     * of this type under them, so this is retained for legacy purposes.
     */
    @Deprecated
    DOMAIN_ALLOCATE,
    /**
     * Used for domain registration autorenews explicitly logged by {@link
     * google.registry.batch.ExpandRecurringBillingEventsAction}.
     */
    DOMAIN_AUTORENEW,
    DOMAIN_CREATE,
    DOMAIN_DELETE,
    DOMAIN_RENEW,
    DOMAIN_RESTORE,
    DOMAIN_TRANSFER_APPROVE,
    DOMAIN_TRANSFER_CANCEL,
    DOMAIN_TRANSFER_REJECT,
    DOMAIN_TRANSFER_REQUEST,
    DOMAIN_UPDATE,
    HOST_CREATE,
    HOST_DELETE,
    HOST_DELETE_FAILURE,
    HOST_PENDING_DELETE,
    HOST_UPDATE,
    /** Resource was created by an escrow file import. */
    RDE_IMPORT,
    /**
     * A synthetic history entry created by a tool or back-end migration script outside the scope of
     * usual EPP flows. These are sometimes needed to serve as parents for billing events or poll
     * messages that otherwise wouldn't have a suitable parent.
     */
    SYNTHETIC
  }

  /**
   * The autogenerated id of this event. Note that, this field is marked as {@link Transient} in the
   * SQL schema, this is because the child class of {@link HistoryEntry}, e.g. {@link
   * DomainHistory}, uses a composite primary key which the id is part of, and Hibernate requires
   * that all the {@link javax.persistence.Id} fields must be put in the exact same class.
   */
  @OfyIdAllocation @Transient @VisibleForTesting public Long id;

  /** The type of history entry. */
  @Column(nullable = false, name = "historyType")
  @Enumerated(EnumType.STRING)
  Type type;

  /**
   * The length of time that a create, allocate, renewal, or transfer request was issued for. Will
   * be null for all other types.
   */
  @Transient // domain-specific
  Period period;

  /**
   * The actual EPP xml of the command, stored as bytes to be agnostic of encoding.
   *
   * <p>Changes performed by backend actions would not have EPP requests to store.
   */
  @Column(name = "historyXmlBytes")
  byte[] xmlBytes;

  /** The time the command occurred, represented by the ofy transaction time. */
  @Column(nullable = false, name = "historyModificationTime")
  DateTime modificationTime;

  /** The id of the registrar that sent the command. */
  @Column(name = "historyRegistrarId")
  String clientId;

  /**
   * For transfers, the id of the other registrar.
   *
   * <p>For requests and cancels, the other registrar is the losing party (because the registrar
   * sending the EPP transfer command is the gaining party). For approves and rejects, the other
   * registrar is the gaining party.
   */
  @Transient // domain-specific
  String otherClientId;

  /** Transaction id that made this change, or null if the entry was not created by a flow. */
  @Nullable
  @AttributeOverrides({
    @AttributeOverride(
        name = "clientTransactionId",
        column = @Column(name = "historyClientTransactionId")),
    @AttributeOverride(
        name = "serverTransactionId",
        column = @Column(name = "historyServerTransactionId"))
  })
  Trid trid;

  /** Whether this change was created by a superuser. */
  @Column(nullable = false, name = "historyBySuperuser")
  boolean bySuperuser;

  /** Reason for the change. */
  @Column(name = "historyReason")
  String reason;

  /** Whether this change was requested by a registrar. */
  @Column(name = "historyRequestedByRegistrar")
  Boolean requestedByRegistrar;

  /**
   * Logging field for transaction reporting.
   *
   * <p>This will be empty for any {@link HistoryEntry} generated before this field was added. This
   * will also be empty if the {@link HistoryEntry} refers to an EPP mutation that does not affect
   * domain transaction counts (such as contact or host mutations).
   */
  @Transient // domain-specific
  @EmptySetToNull
  protected Set<DomainTransactionRecord> domainTransactionRecords;

  protected long getId() {
    // For some reason, Hibernate throws NPE during some initialization phases if we don't deal with
    // the null case. Setting the id to 0L when it is null should be fine because 0L for primitive
    // type is considered as null for wrapper class in the Hibernate context.
    return id == null ? 0L : id;
  }

  /** This method exists solely to satisfy Hibernate. Use the {@link Builder} instead. */
  @SuppressWarnings("unused")
  private void setId(long id) {
    this.id = id;
  }

  public Type getType() {
    return type;
  }

  public Period getPeriod() {
    return period;
  }

  public byte[] getXmlBytes() {
    return xmlBytes;
  }

  public DateTime getModificationTime() {
    return modificationTime;
  }

  public String getRegistrarId() {
    return clientId;
  }

  public String getOtherRegistrarId() {
    return otherClientId;
  }

  /** Returns the TRID, which may be null if the entry was not created by a normal flow. */
  @Nullable
  public Trid getTrid() {
    return trid;
  }

  public boolean getBySuperuser() {
    return bySuperuser;
  }

  public String getReason() {
    return reason;
  }

  public Boolean getRequestedByRegistrar() {
    return requestedByRegistrar;
  }

  public Set<DomainTransactionRecord> getDomainTransactionRecords() {
    return nullToEmptyImmutableCopy(domainTransactionRecords);
  }

  /** Throws an error when attempting to retrieve the EppResource at this point in time. */
  public abstract Optional<? extends EppResource> getResourceAtPointInTime();

  /** This method exists solely to satisfy Hibernate. Use the {@link Builder} instead. */
  @SuppressWarnings("unused")
  private void setPeriod(Period period) {
    this.period = period;
  }

  /** This method exists solely to satisfy Hibernate. Use the {@link Builder} instead. */
  @SuppressWarnings("unused")
  private void setOtherRegistrarId(String otherRegistrarId) {
    this.otherClientId = otherRegistrarId;
  }

  /** This method exists solely to satisfy Hibernate. Use the {@link Builder} instead. */
  @SuppressWarnings("unused")
  protected void setDomainTransactionRecords(
      Set<DomainTransactionRecord> domainTransactionRecords) {
    // Note: how we wish to treat this Hibernate setter depends on the current state of the object
    // and what's passed in. The key principle is that we wish to maintain the link between parent
    // and child objects, meaning that we should keep around whichever of the two sets (the
    // parameter vs the class variable) and clear/populate that as appropriate.
    //
    // If the class variable is a PersistentSet, and we overwrite it here, Hibernate will throw
    // an exception "A collection with cascade=”all-delete-orphan” was no longer referenced by the
    // owning entity instance". See https://stackoverflow.com/questions/5587482 for more details.
    if (this.domainTransactionRecords instanceof PersistentSet) {
      Set<DomainTransactionRecord> nonNullRecords = nullToEmpty(domainTransactionRecords);
      this.domainTransactionRecords.retainAll(nonNullRecords);
      this.domainTransactionRecords.addAll(nonNullRecords);
    } else {
      this.domainTransactionRecords = domainTransactionRecords;
    }
  }

  @Override
  public abstract Builder<? extends HistoryEntry, ?> asBuilder();

  protected static void copy(HistoryEntry src, HistoryEntry dst) {
    dst.id = src.id;
    dst.type = src.type;
    dst.period = src.period;
    dst.xmlBytes = src.xmlBytes;
    dst.modificationTime = src.modificationTime;
    dst.clientId = src.clientId;
    dst.otherClientId = src.otherClientId;
    dst.trid = src.trid;
    dst.bySuperuser = src.bySuperuser;
    dst.reason = src.reason;
    dst.requestedByRegistrar = src.requestedByRegistrar;
    dst.domainTransactionRecords =
        src.domainTransactionRecords == null
            ? null
            : ImmutableSet.copyOf(src.domainTransactionRecords);
  }

  /** A builder for {@link HistoryEntry} since it is immutable */
  public abstract static class Builder<T extends HistoryEntry, B extends Builder<?, ?>>
      extends GenericBuilder<T, B> {
    protected Builder() {}

    protected Builder(T instance) {
      super(instance);
    }

    // Used to fill out the fields in this object from an object which may not be exactly the same
    // as the class T, where both classes still subclass HistoryEntry
    public B copyFrom(HistoryEntry historyEntry) {
      copy(historyEntry, getInstance());
      return thisCastToDerived();
    }

    public B copyFrom(HistoryEntry.Builder<? extends HistoryEntry, ?> builder) {
      return copyFrom(builder.getInstance());
    }

    @Override
    public T build() {
      // TODO(mcilwain): Add null checking for id/parent once DB migration is complete.
      checkArgumentNotNull(getInstance().type, "History entry type must be specified");
      checkArgumentNotNull(getInstance().modificationTime, "Modification time must be specified");
      checkArgumentNotNull(getInstance().clientId, "Registrar ID must be specified");
      checkArgument(
          !getInstance().type.equals(Type.SYNTHETIC)
              || BooleanUtils.isNotTrue(getInstance().requestedByRegistrar),
          "Synthetic history entries cannot be requested by a registrar");
      return super.build();
    }

    public B setId(Long id) {
      getInstance().id = id;
      return thisCastToDerived();
    }

    public B setType(Type type) {
      getInstance().type = type;
      return thisCastToDerived();
    }

    public B setPeriod(Period period) {
      getInstance().period = period;
      return thisCastToDerived();
    }

    public B setXmlBytes(byte[] xmlBytes) {
      getInstance().xmlBytes = xmlBytes;
      return thisCastToDerived();
    }

    public B setModificationTime(DateTime modificationTime) {
      getInstance().modificationTime = modificationTime;
      return thisCastToDerived();
    }

    public B setRegistrarId(String registrarId) {
      getInstance().clientId = registrarId;
      return thisCastToDerived();
    }

    public B setOtherRegistrarId(String otherRegistrarId) {
      getInstance().otherClientId = otherRegistrarId;
      return thisCastToDerived();
    }

    public B setTrid(Trid trid) {
      getInstance().trid = trid;
      return thisCastToDerived();
    }

    public B setBySuperuser(boolean bySuperuser) {
      getInstance().bySuperuser = bySuperuser;
      return thisCastToDerived();
    }

    public B setReason(String reason) {
      getInstance().reason = reason;
      return thisCastToDerived();
    }

    public B setRequestedByRegistrar(Boolean requestedByRegistrar) {
      getInstance().requestedByRegistrar = requestedByRegistrar;
      return thisCastToDerived();
    }

    public B setDomainTransactionRecords(
        ImmutableSet<DomainTransactionRecord> domainTransactionRecords) {
      getInstance().setDomainTransactionRecords(domainTransactionRecords);
      return thisCastToDerived();
    }
  }

  public static <E extends EppResource>
      HistoryEntry.Builder<? extends HistoryEntry, ?> createBuilderForResource(E parent) {
    if (parent instanceof DomainBase) {
      return new DomainHistory.Builder().setDomain((DomainBase) parent);
    } else if (parent instanceof ContactBase) {
      return new ContactHistory.Builder().setContact((ContactBase) parent);
    } else if (parent instanceof HostBase) {
      return new HostHistory.Builder().setHost((HostBase) parent);
    } else {
      throw new IllegalStateException(
          String.format(
              "Class %s does not have an associated HistoryEntry", parent.getClass().getName()));
    }
  }

  public abstract static class HistoryEntryId extends ImmutableObject
      implements UnsafeSerializable {

    private long id;

    protected HistoryEntryId() {}

    public long getId() {
      return id;
    }

    public void setId(long id) {
    this.id = id;
    }

  }
}
